language: go
go: 1.x

env:
  - PATH=$PATH:$GOPATH/bin GO111MODULE=on

install:
  - go mod download

script:
  - go test -v

before_deploy:
  - bin/deploy-compile.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
      secure: iwKAXW8xheZ/zoDKrHmud7I8uAhTSaNKYDrSdTdD6P6voBLkJHUEV7G2xpTbdGTKlYtLIKOZ3qcV4igz8bYLY5HIbrqVqYV91Nth2LAaivZTM2GUGLZIMrt214nSt1QBPKefqCyVWWu+/KxMBSSWZIH/q/99dO9zlgOHaduhqcpfQ//a/SVeJFPuyPli5za6SVXjznBPlEszKrUWCYhZsyj+OCq13oh9hBeZ/dNS3vBlVXGYUgL4957DEsG7HCBMJRlaUFZdNtMfcjpjJkHWygTl3CYxr2ikpWlLLFw3/rM05ZcAXoSf3AcxRMWNEXdIIoUWiRbr2hABJNO1G6Bqbu/FXntLSs8wXkXRCdnaSu5ux4Nx/9GQJXwrekxA8yu8Kgg59NqPJRs0dTq3Ou+JJRf1jeLZlQ3bB0klslZ2ig0LTtmoTMrejFZkYwxzwJWtwnLfiB2Dc4BmqA73/xbLDi2+XHE1gsZ8vq9YF/Rt4u5H5mWvtA+PBRGOVKWt+lXJjyaJ7trKw9vv6NmfgbggNUi3I4ZCMphUMiK+fEzvYO/dqY3B9x2dIXgz3vdVC5F2HXehb5Fhjla2FLGlkN6oplY1gIpv/KfjeoRhcuLwtjCDXq2QFUV3MATBsAq6znCwPyXLSXgBgCD3nPOc0+0s64aj/lNd5Wp5s/fKWKRRilM=
  file_glob: true
  file: target/*
  on:
    repo: nickw444/cf-ddns
    tags: true
